# Numpy Exercise  <img src = "numpy1.png">
###### Authored by T.K.Senthil Kumar

In [ ]:
# 1. Create a numpy array with the number of elements equals your age. The value of array elements is a random number between 10 to your age 

In [1]:
age= int(input('Enter your age'))
import numpy as np
ar=np.random.randint(10,age,age)
ar

Enter your age25


array([10, 17, 17, 21, 16, 24, 19, 15, 11, 11, 11, 23, 18, 22, 20, 11, 11,
       16, 15, 23, 10, 11, 12, 23, 21])

#### 2. Create a numpy array between 1 to 50 with the span(space) of 2 and print the length of the array

In [2]:
# Solution
ar1=np.arange(1,50,2)
print(len(ar1))




25


#### 3. Create an equally spaced numpy array with 27 elements between 4 and 7 

In [3]:
# Solution
ar2=np.linspace(4,7,27)
ar2



array([4.        , 4.11538462, 4.23076923, 4.34615385, 4.46153846,
       4.57692308, 4.69230769, 4.80769231, 4.92307692, 5.03846154,
       5.15384615, 5.26923077, 5.38461538, 5.5       , 5.61538462,
       5.73076923, 5.84615385, 5.96153846, 6.07692308, 6.19230769,
       6.30769231, 6.42307692, 6.53846154, 6.65384615, 6.76923077,
       6.88461538, 7.        ])

#### 4. Create a matrix of size (5 x 4) with random numbers and round off the each elements by only 2 fractional points.

In [4]:
# Solution
matA=np.random.random((5,4))
round_matA=np.round(matA,2)
round_matA



array([[0.36, 0.03, 0.59, 0.4 ],
       [0.97, 0.94, 0.68, 0.19],
       [0.4 , 0.11, 0.87, 0.24],
       [0.25, 0.12, 0.56, 0.65],
       [0.53, 0.46, 0.05, 0.09]])

#### 5. Create a matrix of size (5x5) with random integers between 5 to 15

In [5]:
# Solution
matB=np.random.randint(5,15,(5,5))
matB



array([[ 8,  7,  5,  8, 10],
       [ 9,  9, 13,  8, 12],
       [12,  5, 11,  5, 13],
       [ 8,  9,  6, 13, 10],
       [ 8, 10, 10,  5,  9]])

#### 6. Create the one dimensional array of zeros of random length below 20 with the data type int32

In [6]:
# Solution
np.random.seed(100)
rand_num=np.random.randint(0,20,1)
rand_num
arr=np.zeros(rand_num,dtype=int)
arr



array([0, 0, 0, 0, 0, 0, 0, 0])

#### 7. Create a two dimensional array of ones of random row and column lengths with the data type of float32 

In [7]:
# Solution

rand1=np.random.randint(10)
rand2=np.random.randint(10)
arr=np.ones((rand1,rand2),dtype=float)
arr



array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### 8. Create a matrix exactly as same as shown below and print its shape, type and dtype
<img src = "np_mat1.png">

In [8]:
# Solution
matrix1=np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,54,6],[23,12,8,5,8]])
print("matrix is" ,matrix1)
print("matrix shape",matrix1.shape)
print("Matrix type",type(matrix1))
print("matrix datatype",matrix1.dtype)



matrix is [[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6 54  6]
 [23 12  8  5  8]]
matrix shape (5, 5)
Matrix type <class 'numpy.ndarray'>
matrix datatype int32


#### 9. Access the center pixel of the matrix defined in the question no 8 ( Don't enter the row and column index explicitely)

In [9]:
# Solution
x=matrix1.flatten()
center_pixel=x[(len(x)//2)]
print("Center pixel of given matrix is",center_pixel)


Center pixel of given matrix is 3


#### 10. Print the all the elements of 3rd row of the matrix

In [10]:
# Solution
print(matrix1[2:3,])



[[ 5  7  3 76  3]]


#### 11. Print the all the elements of 4th columns of the matrix

In [11]:
# Solution
print(matrix1[0:,3:4])



[[34]
 [65]
 [76]
 [54]
 [ 5]]


#### 12. Print the 4 corner pixels of the matrix

In [12]:
# Solution
r=len(matrix1)#to find the number of rows
c=len(matrix1[0])# to find number of columns
corner1=matrix1[0][0]
corner2=matrix1[0][c-1]
corner3=matrix1[r-1][0]
corner4=matrix1[r-1][c-1]
c_elements=np.array([corner1,corner2,corner3,corner4])
print("The corner pixels are",c_elements)


The corner pixels are [ 9 45 23  8]


#### 13. Create three matrix m1,m2,m3 with the elements grouped in the figure below
<img src = "np_mat2.png">

In [13]:
# Solution 
m1=matrix1[0:2,2:4]
print(m1)
m2=matrix1[3:,0:2]
print(m2)
m3=matrix1[2:,2:]
print(m3)


[[50 34]
 [34 65]]
[[ 7  8]
 [23 12]]
[[ 3 76  3]
 [ 6 54  6]
 [ 8  5  8]]


#### 14. Reshape all the three matrix segmented in the above task in to three  1-dimensional vector.

In [14]:
# Solution
reshape_m1=m1.flatten()
reshape_m2=m2.flatten()
reshape_m3=m3.flatten()
print("Reshaped m1 is",reshape_m1)
print("Reshaped m2 is",reshape_m2)
print("Reshaped m3 is",reshape_m3)



Reshaped m1 is [50 34 34 65]
Reshaped m2 is [ 7  8 23 12]
Reshaped m3 is [ 3 76  3  6 54  6  8  5  8]


#### 15. Concatenate the matrix m1 and m2 in both vertical and horizontal direction

In [15]:
# Solution
m_4=np.concatenate((m1,m2),axis=0)
print(m_4)
m_5=np.concatenate((m1,m2),axis=1)
print(m_5)

[[50 34]
 [34 65]
 [ 7  8]
 [23 12]]
[[50 34  7  8]
 [34 65 23 12]]


#### 16. Add, Subtract, multiply, divide the matrixes m1 and m2

In [16]:
# Solution
m_add=m1+m2
print(m_add)
m_sub=m1-m2
print(m_sub)
m_mul=m1*m2
print(m_mul)
m_div=m1/m2
print(m_div)



[[57 42]
 [57 77]]
[[43 26]
 [11 53]]
[[350 272]
 [782 780]]
[[7.14285714 4.25      ]
 [1.47826087 5.41666667]]


#### 17. Add the m1 with m3 by removing the first row and last column of m3

In [17]:
# Solution

m3=np.delete(m3,(0),axis=0)
m_del_1=np.delete(m3,(-1),axis=1)

m_addition=m1+m_del_1
print(m_addition)

[[56 88]
 [42 70]]


#### 18. Form the matrix m4 by concatenating (as a new row) the vector [me1, me2] with the matrix m1, where me1 and me2 are the mean values of each column on m1.

In [18]:
me=m1.mean(axis=1)
me=me.reshape(1,2)
m1.shape
m4=np.concatenate((m1,me),axis=0)
print(m4)



[[50.  34. ]
 [34.  65. ]
 [42.  49.5]]


#### 19. Perform the matrix multiplication between m3 and m4

In [38]:
# Solution
m3=matrix1[2:,2:]
m3.shape
m4.shape
m_multi=np.matmul(m3,m4)
print(m_multi)


[[2860.  5190.5]
 [2388.  4011. ]
 [ 906.   993. ]]


#### 20. Compute the maximum and minimum value of mean, variance, standard deviation for each row of matrix created in question number 8.

In [20]:
# Solution
mean1=matrix1.mean(axis=0)
var1=matrix1.var(axis=0)
std1=matrix1.std(axis=0)
print(mean1)
print(var1)
print(std1)
print("maximum mean",mean1.max())
print("minimum mean",mean1.min())
print("maximum variance",var1.max())
print("minimum variance",var1.mean())
print("maximum standard deviation",std1.max())
print("minimum standard deviation",std1.min())


[ 9.4 17.2 20.2 46.8 12.8]
[ 50.24 111.76 344.96 629.36 263.76]
[ 7.08801806 10.57166023 18.57309883 25.08704845 16.24068964]
maximum mean 46.8
minimum mean 9.4
maximum variance 629.36
minimum variance 280.01599999999996
maximum standard deviation 25.08704845134238
minimum standard deviation 7.08801805866774


#### 21. Compute the average and strike rate for each player and sort it decending way (seperately for avg and strike rate)
<img src = 'crick1.png'>

In [34]:
# Solution 
run_scored=np.array([[54,60,10,65],[102,2,78,32],[3,110,1,92],[56,6,12,42],[12,8,22,11]])
balls_faced=np.array([[50,42,22,78],[95,8,65,43],[9,100,7,101],[27,3,11,31],[24,20,36,27]])
MSD_avg=np.average(run_scored[0:1,0:])
Kholi_avg=np.average(run_scored[1:2,0:])
Rohit_avg=np.average(run_scored[2:3,0:])
Rahul_avg=np.average(run_scored[3:4,0:])
Dhawan_avg=np.average(run_scored[4:,0:])
Average_team=np.array([MSD_avg,Kholi_avg,Rohit_avg,Rahul_avg,Dhawan_avg])
Average_team=np.sort(Average_team)
print("Average of the team is",Average_team)
print("Average of team in descending is",Average_team[::-1])

Strike_rate=(run_scored/balls_faced)*100
MSD_st=Strike_rate[0:1,0:].mean()
Kholi_st=Strike_rate[1:2,0:].mean()
Rohit_st=Strike_rate[2:3,0:].mean()
Rahul_st=Strike_rate[3:4,0:].mean()
Dhawan_st=Strike_rate[4:5,0:].mean()
strike_team=np.array([MSD_st,Kholi_st,Rohit_st,Rahul_st,Dhawan_st])
strike_team=np.sort(strike_team)
print('Strike rate of team',strike_team)
print("Strike rate of team in descending ",strike_team[::-1])


Average of the team is [13.25 29.   47.25 51.5  53.5 ]
Average of team in descending is [53.5  51.5  47.25 29.   13.25]
Strike rate of team [ 47.96296296  62.17703913  81.69675643  94.91125541 162.99554687]
Strike rate of team in descending  [162.99554687  94.91125541  81.69675643  62.17703913  47.96296296]


#### 22. The students mark was recorded in a numpy array: marks = np.array([65,84,47,56,89,98,48,77,80,39]).  Cutoff for pass is 50 marks. Write the logic to print the number of students passed and failed. 

In [35]:
# Solution
marks = np.array([65,84,47,56,89,98,48,77,80,39])
failed_stud=(marks<50).sum()
print("No.of failed students",failed_stud)
passed_stud=(marks>=50).sum()
print("No.of passed students",passed_stud)



No.of failed students 3
No.of passed students 7


#### 23. The class incharge decided to give a mercy mark of 5 for those who scored between 45 and 49. Also the bonus of 5 marks awarded to the students who scored more than 80. Print all the student marks and compute the increase in the pass percentage of class. Any score more than 100 must be recorded as only 100.

In [36]:
# Solution
for i in range (0,len(marks)):
    if marks[i]>45 and marks[i]<50:
        marks[i]=marks[i]+ 5
    elif marks[i]>80:
        marks[i]=marks[i]+5
ind=np.where(marks>100)
marks[ind]=100
print(marks)




[ 65  89  52  56  94 100  53  77  80  39]


#### 24. Print the time taken for performing the following operation using list and numpy array
####       (x(i)^2 +8) / y(i),   where x and y are real integers from 1 to 60000

In [50]:
# Solution
import time
def lst():
    x=list(range(1,60000))
    y=list(range(1,60000))
    result=[]
    for i in range(len(x)):
        result.append((((x[i]**2)+8)/y[i]))
def npy():
        x=np.array(range(1,60000))
        y=np.array(range(1,60000))
        result=((x**2)+8)/y
start=time.time()
%time lst()
end=time.time()
print("Time taken for list is",end-start)
start1=time.time()
%time npy()
end1=time.time()
print("Time taken for numpy is",end1-start1)
    
    




Wall time: 92 ms
Time taken for list is 0.0959465503692627
Wall time: 30 ms
Time taken for numpy is 0.0319819450378418


#### 25. Create a Github account and upload your solution with the short write-up on Numpy

In [ ]:
# Solution



